#!/bin/bash
#Author: Chintan Murty


export SUDO_ASKPASS=sudo_pass
sudoPassDir="${HOME}/.config/sudoPass"
sudoPassFile="${sudoPassDir}/myPass"
debug=false

#[sudo] password for cmmurty: 


setPass()
{
	mkdir -p $sudoPassDir && touch $sudoPassFile
	if [ $? -eq 0 ]
	then
		chmod 700 $sudoPassDir
		read -s -p "Enter you password :" sudoPass
		echo $sudoPass >$sudoPassFile
		chmod 600 $sudoPassFile 
		echo
		echo 'Password set.'
	       	echo 'Now, set envirnment variable "SUDO_ASKPASS" and alias for sudo to "sudo -A" by running below command.'
		echo 'export SUDO_ASKPASS=${HOME}/bin/sudo_pass && alias sudo="sudo -A"'
	else
		echo "Error: Couldn't create config directory [$sudoPassDir] or file [$sudoPassFile]" 
		exit 3
	fi
}

getPass()
{
	if [ -e "$sudoPassFile" ]
	then
		echo "sudo_pass passing password." |logger -t "sudo_pass"
		cat $sudoPassFile | tr --delete "\n"
		exit 0
	else
		echo "There was an error getting password." |logger -t "sudo_pass"
		echo 'Error: no password set. Run "sudo_pass -s" to set password before using "sudo -A"' >&2
		exit 2
	fi
}

clearPass()
{

	if [ -e "$sudoPassFile" ]
	then
		rm -f $sudoPassFile
		if [ $? -eq 0 ]
		then
			echo "Password file removed"
		else
			echo "Error: There was an error while removing password file [$sudoPassFile]" >&2
			exit 4
		fi
	else
		echo "No password file found [$sudoPassFile]"
		exit 0
	fi

}

printHelp()
{
	echo "Will tell you later how to use it."
}


if [ "$#" -eq 1 ]
then

	if [ "$1" == "-s" ]
	then
		echo "Setting password" |logger -t "sudo_pass"
		setPass
	elif [ "$1" == "[sudo] password for ${USER}: " ]
	then
		getPass
		echo "Password fetched by sudo for user $USER" | logger -t "sudo_pass"
	elif [ "$1" == "-c" ]
	then
        	echo "Setting password" |logger -t "sudo_pass"
	        clearPass
	else
		echo "Nothing matched." |logger -t "sudo_pass"
		printHelp
		exit 1
	fi

else
	printHelp
	exit 1
fi

exit 0
